# Path: Deep_Learning_Trading_Robot/config/config.yaml
# General configuration for the trading robot
trading:
  broker_api_key: 'your_broker_api_key'
  model_update_frequency: 'daily'
  risk_tolerance: 0.02  # Max risk per trade (2%)
data:
  data_source: 'alpha_vantage'
  update_frequency: 'daily'
