data_fetching:
  backoff_factor: 2.0
  fetch_retries: 3
limit: 1000
logging:
  backup_count: 2
  log_dir: ./logs
  log_file: robot.log
  log_level: INFO
  max_log_size: 5242880
notification: {}
strategy:
  ema_length: 8
  rsi_length: 14
  rsi_overbought: 70.0
  rsi_oversold: 30.0
symbol: TSLA
timeframe: 1d
